"""Export analysis report as downloadable HTML file."""
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from backend.services.cache import cache

router = APIRouter(prefix="/api")


@router.get("/export/{repo_hash}")
async def export_report(repo_hash: str):
    """Generate a downloadable HTML report for the given repo hash."""
    result = cache.get_by_hash(repo_hash)
    if not result:
        from backend.services.storage import get_by_url_hash
        result = get_by_url_hash(repo_hash)
    if not result:
        raise HTTPException(status_code=404, detail="Report not found")

    health = result["health_score"]
    badge = result["badge_level"]
    color = result.get("badge_color", "lightgrey")
    dimensions = result.get("dimensions", [])
    diagnosis = result.get("ai_diagnosis", [])
    repo = result.get("repo_url", "")

    _badge_colors = {"brightgreen": "#4c1", "yellow": "#dfb317", "orange": "#fe7d37", "red": "#e05d44"}

    dim_rows = "".join(
        f"""<tr>
            <td>{d['dimension']}</td>
            <td>{d['score']}/100</td>
            <td><div style="background:#e5e7eb;border-radius:4px;height:12px"><div style="background:{'#22c55e' if d['score']>=75 else '#eab308' if d['score']>=50 else '#ef4444'};width:{d['score']}%;height:12px;border-radius:4px"></div></div></td>
        </tr>"""
        for d in dimensions
    )

    diag_rows = "".join(
        f"""<div style="padding:8px 0;border-bottom:1px solid #e5e7eb">
            <strong style="color:{'#ef4444' if s['severity']=='high' else '#eab308' if s['severity']=='medium' else '#3b82f6'}">[{s['severity'].upper()}]</strong>
            {s['advice']}
            <span style="color:#888;font-size:12px">置信度 {s['confidence']}% · 约 {s['estimated_hours']}h</span>
        </div>"""
        for s in diagnosis
    )

    html = f"""<!DOCTYPE html>
<html lang="zh">
<head><meta charset="utf-8"><title>Repo Health Report - {repo}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:32px;max-width:680px;margin:0 auto;color:#1e293b}}
h1{{font-size:24px;margin-bottom:4px}}
.sub{{color:#64748b;font-size:13px;margin-bottom:20px}}
.score{{font-size:32px;font-weight:700;color:{_badge_colors.get(color, '#9f9f9f')}}}
.badge{{display:inline-block;padding:2px 12px;border-radius:10px;background:{_badge_colors.get(color, '#9f9f9f')};color:#fff;font-weight:700;font-size:14px;margin-left:8px;vertical-align:super}}
h2{{font-size:16px;margin:20px 0 12px;padding-bottom:6px;border-bottom:2px solid #e2e8f0}}
table{{width:100%;border-collapse:collapse}}
td{{padding:8px 0;font-size:14px}}td:first-child{{font-weight:600;width:160px}}td:last-child{{width:200px}}
@media print{{body{{padding:16px}}@page{{margin:1cm}}}}
</style></head>
<body>
<h1>Repo Health Report</h1>
<p class="sub">{repo}</p>
<div><span class="score">{health}/100</span><span class="badge">{badge}</span></div>
<h2>六维度评分</h2>
<table>{dim_rows}</table>
{('<h2>AI 诊断建议</h2>' + diag_rows) if diag_rows else ''}
<p style="margin-top:24px;color:#94a3b8;font-size:12px">Generated by Repo Health Check · {result.get('analyzed_at', '')[:10]}</p>
</body></html>"""

    filename = repo.replace("https://github.com/", "").replace("/", "-") + "-health-report.html"
    return Response(
        content=html,
        media_type="text/html",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
