version: 2
name: repo-health-ci
description: Repo Health Check CI for GitLink/Jianmu

global:
  concurrent: 1

trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: push
      ruleset-operator: AND

workflow:
  - ref: start
    name: start
    task: start

  - ref: backend_ci
    name: backend-ci
    image: docker.m.daocloud.io/library/python:3.11-bookworm
    script:
      - git --version && rm -rf /tmp/repo-health-check && git clone --depth=1 --branch master https://gitlink.org.cn/LINGQvQ/repo-health-check.git /tmp/repo-health-check && cd /tmp/repo-health-check && sh devops/gitlink/backend-ci.sh
    needs:
      - start

  - ref: frontend_ci
    name: frontend-ci
    image: docker.m.daocloud.io/library/node:20-bookworm
    script:
      - git --version && rm -rf /tmp/repo-health-check && git clone --depth=1 --branch master https://gitlink.org.cn/LINGQvQ/repo-health-check.git /tmp/repo-health-check && cd /tmp/repo-health-check && sh devops/gitlink/frontend-ci.sh
    needs:
      - backend_ci

  - ref: end
    name: end
    task: end
    needs:
      - frontend_ci
