import { normalizeBadgeColor } from './reportAssets';

export interface ComparePosterResult {
  repo_url: string;
  health_score: number;
  badge_level: string;
  badge_color: string;
}

function repoName(url: string): string {
  return url.replace(/^https?:\/\/github\.com\//, '');
}

function fitText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text;
  let next = text;
  while (next.length > 4 && ctx.measureText(`${next}...`).width > maxWidth) {
    next = next.slice(0, -1);
  }
  return `${next}...`;
}

function roundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function drawFighter(ctx: CanvasRenderingContext2D, result: ComparePosterResult, x: number, align: 'left' | 'right') {
  const color = normalizeBadgeColor(result.badge_color);
  ctx.fillStyle = 'rgba(255,255,255,0.08)';
  roundedRect(ctx, x, 176, 430, 260, 28);
  ctx.fill();
  ctx.strokeStyle = 'rgba(255,255,255,0.16)';
  ctx.stroke();

  ctx.fillStyle = color;
  roundedRect(ctx, x + 28, 204, 126, 42, 14);
  ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.font = '800 22px "Segoe UI", sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText(result.badge_level, x + 91, 232);

  ctx.textAlign = align;
  ctx.fillStyle = '#e2e8f0';
  ctx.font = '800 32px "Segoe UI", sans-serif';
  ctx.fillText(fitText(ctx, repoName(result.repo_url), 360), align === 'left' ? x + 30 : x + 400, 292);

  ctx.fillStyle = '#fff';
  ctx.font = '900 92px "Segoe UI", sans-serif';
  ctx.fillText(String(Math.round(result.health_score)), align === 'left' ? x + 30 : x + 400, 390);
}

export function downloadComparePoster(repoA: ComparePosterResult, repoB: ComparePosterResult): void {
  const canvas = document.createElement('canvas');
  canvas.width = 1200;
  canvas.height = 630;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const winner = repoA.health_score >= repoB.health_score ? repoA : repoB;
  const gradient = ctx.createLinearGradient(0, 0, 1200, 630);
  gradient.addColorStop(0, '#09111f');
  gradient.addColorStop(0.5, '#312e81');
  gradient.addColorStop(1, '#111827');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 1200, 630);

  ctx.fillStyle = 'rgba(45,212,191,0.12)';
  ctx.beginPath();
  ctx.arc(600, 315, 260, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = '#c4b5fd';
  ctx.font = '700 30px "Segoe UI", sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Repo Health PK Arena', 600, 92);

  ctx.fillStyle = '#fff';
  ctx.font = '900 48px "Segoe UI", sans-serif';
  ctx.fillText(`${repoName(winner.repo_url)} wins`, 600, 146);

  drawFighter(ctx, repoA, 76, 'left');
  drawFighter(ctx, repoB, 694, 'right');

  ctx.fillStyle = '#fff';
  ctx.font = '900 68px "Segoe UI", sans-serif';
  ctx.fillText('VS', 600, 340);

  ctx.fillStyle = '#94a3b8';
  ctx.font = '600 22px "Segoe UI", sans-serif';
  ctx.fillText('Generated by Repo Health Check', 600, 542);

  const link = document.createElement('a');
  link.download = `${repoName(repoA.repo_url).replace(/[^\w.-]+/g, '-')}-vs-${repoName(repoB.repo_url).replace(/[^\w.-]+/g, '-')}.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}
